CRMNCC/crm/accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'


urlpatterns = [

    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('profile/eit/', views.profile_edit, name='profile_edit'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
    path('password_reset/',auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('reset/', views.reset, name='reset'),
    ]

CRMNCC/crm/crm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('crmapp/', include('crmapp.urls')),
    path('myemail/', include('myemail.urls')),

]

CRMNCC/crm/crmapp/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name='index'),
    path('home/', views.index, name='home'),

    path('customers/', views.customerslist, name='customerslist'),
    path('customer/new/', views.customernew, name='customernew'),
    path('customer/<pk>/', views.customerDetailView.as_view(), name='customerdetail'),
    path('customer/update/<pk>/', views.customerUpdateView.as_view(), name='customerupdate'),

    path('opportunity/new/', views.opportunitynew, name='newopportunity'),
    path('opportunityc/new/<pk>', views.opportunitycnew, name='newopportunityc'),
    path('opportunity/<pk>/', views.opportunitydetail, name='opportunitydetail'),
    path('opportunity/', views.opportunitylist, name='opportunitylist'),
    path('opportunity/update/<pk>/', views.opportunityUpdateView.as_view(), name='opportunityupdate'),
    path('opportunity/proposal/<pk>/', views.proposalopp, name='proposal'),
    path('opportunity/document/<pk>/', views.documentopp, name='document'),
    path('opportunity/negotiation/<pk>/', views.negotiationopp, name='negotiation'),
    path('opportunity/operationvalidation/<pk>/', views.operationvalidationopp, name='operationvalidation'),
    path('opportunity/validated/<pk>/', views.validatedopp, name='validated'),
    path('opportunity/post/<pk>/', views.postopp, name='postopp'),
    path('opportunity/lost/<pk>/', views.lostopp, name='lost'),
    path('opportunity/stcapproval/<pk>/', views.stcapproval, name='stcapproval'),
    path('operval/', views.operval, name='operval'),
    path('opportunitypost/', views.opportunitypost, name='opportunitypost'),

    path('addservice/new/<pk>/', views.addservicenew, name='addservice'),
    path('addservice/list/', views.addserviceslist, name='addservicelist'),

    path('staff/', views.stafflist, name='stafflist'),
    path('staff/new/', views.CreatestaffView.as_view(), name='staffnew'),
    path('staff/<pk>/', views.staffDetailView.as_view(), name='staffdetail'),

    path('suggestion/', views.suggestionlist, name='suggestion'),
    path('suggestion/new/', views.suggestionnew, name='suggestionnew'),
    path('suggestion/<pk>/', views.suggestionDetailView.as_view(), name='suggestiondetail'),
    path('suggestion/update/<pk>/', views.suggestionUpdateView.as_view(), name='suggestionupdate'),
    path('suggestion/completion/<pk>/', views.completedsugg, name='completed'),
    path('suggestion/closed/<pk>/', views.closedsugg, name='closed'),

    path('order/', views.orderlist, name='order'),
    path('order/post/', views.orderpostlist, name='orderpost'),
    path('order/open/', views.orderopenlist, name='orderopen'),
    path('order/held/', views.orderheldlist, name='orderheld'),
    path('order/cancel/', views.ordercancellist, name='ordercancel'),
    path('order/new/', views.ordernew, name='ordernew'),
    path('order/<pk>/', views.orderdetail, name='orderdetail'), #new
    path('order/update/<pk>/', views.orderUpdateView.as_view(), name='orderupdate'),
    path('order/changetopost/<pk>/', views.changetopost, name='changetopost'),
    path('order/cancel/<pk>/', views.cancelorder, name='cancel'),
    path('order/open/<pk>/', views.openorder, name='open'),
    path('order/held/<pk>/', views.heldorder, name='held'),
    path('ordero/new/<pk>/<pk1>/', views.orderonew, name='newordero'),
    path('orderdouble/new/<pk>/<pk1>', views.orderdouble, name='orderdouble'),
    path('orderdouble1/new/<pk>/<pk1>', views.orderdouble1, name='orderdouble1'),
    path('orderdouble2/new/<pk>/<pk1>', views.orderdouble2, name='orderdouble2'),
    path('ordernopost', views.ordernopost, name='ordernopost'),
    path('orderupgrade', views.orderupgrade, name='orderupgrade'),
    path('orderfingerprint', views.orderfingerprintlist, name='orderfingerprint'),
    path('orderpaymentupdate/<pk>/', views.orderpaymentupdate, name='orderpaymentupdate'),

    path('stafforderlist/<pk>/', views.stafforderlist, name='stafforderlist'),
    path('orderslistnoactivationdate/', views.orderslistnoactivationdate, name='orderslistnoactivationdate'),



    path('service/', views.servicelist, name='servicelist'),
    path('service/new/', views.CreateserviceView.as_view(), name='servicenew'),
    path('service/<pk>/', views.serviceDetailView.as_view(), name='servicedetail'),
    path('service/update/<pk>/', views.serviceUpdateView.as_view(), name='serviceupdate'),

    path('report/', views.all_users_sum, name='report'),
    path('report/thisyear', views.reportthisyear, name='reportthisyear'),
    path('report/thismonth', views.reportthismonth, name='reportthismonth'),
    path('reportall/', views.reportall, name='reportall'),
    path('report/customer/team', views.reportcustomerteam, name='reportcustomerteam'), #new

    path('report/weak/lastweek', views.reportweaklastweek, name='reportweaklastweek'),#new


    path('dashboard/', views.dashboard, name='dashboard'),
    path('oppnogen/', views.oppnogen, name='oppnogen'),

    path('invoice/new/', views.invoicenew, name='invoicenew'),#new
    path('invoice/<pk>/', views.invoiceDetailView.as_view(), name='invoicedetail'),#new
    path('invoice/update/<pk>/', views.invoiceUpdateView.as_view(), name='invoiceupdate'),#new
    path('invoices/', views.invoiceslist, name='invoiceslist'),#new

    path('expensecategory/new/', views.expensecategorynew, name='expensecategorynew'),#new
    path('expensecategory/<pk>/', views.expensecategoryDetailView.as_view(), name='expensecategorydetail'),#new
    path('expensecategory/update/<pk>/', views.expensecategoryUpdateView.as_view(), name='expensecategoryupdate'),#new
    path('expensecategory/', views.expensecategorylist, name='expensecategorylist'),#new

    path('expenses/new/', views.expensesnew, name='expensesnew'),#new
    path('expenses/<pk>/', views.expensesDetailView.as_view(), name='expensesdetail'),#new
    path('expenses/update/<pk>/', views.expensesUpdateView.as_view(), name='expensesupdate'),#new
    path('expenses/', views.expenseslist, name='expenseslist'),#new
    path('expenses/total', views.expensestotal, name='expensestotal'),#new


    path('mycustomers', views.mycustomers, name='mycustomers'),#new
    path('usercustomers/<pk>/', views.usercustomers, name='usercustomers'),#new

    path('myopportunities', views.myopportunities, name='myopportunities'),#new
    path('useropportunities/<pk>/', views.useropportunities, name='useropportunities'),#new

    path('opportunity/<pk>/delete', views.opportunityDeleteView.as_view(), name='opportunitydelete'), #new


    path('addservice/<pk>/', views.addservicesDetailView.as_view(), name='addservicesdetail'),#new
    path('addservice/<pk>/delete', views.addservicesDeleteView.as_view(), name='addservicedelete'),
    path('addservice/<pk>/delete1', views.addservicesdelete, name='addservicedelete1'),
    path('addservice/update/<pk>/', views.addservicesUpdateView.as_view(), name='addservicesupdate'),
    path('order/<pk>/delete', views.orderDeleteView.as_view(), name='orderdelete'),

    path('order/<pk>/delete1', views.orderdelete, name='orderdelete1'), #new

    path('productreport', views.productreport, name='productreport'),

    path('sourcereport', views.sourcereport, name='sourcereport'),
    path('opportunity/hotlead', views.opportunityhotlead, name='opportunityhotlead'),
    path('customer/oneback', views.customeroneback, name='customeroneback'),
    path('customer/<pk>/assignedto', views.assignedto, name='assignedto'),
    path('pipeline', views.pipeline, name='pipeline'),
    path('megapipeline', views.megapipeline, name='megapipeline'),
    path('operationreport', views.operationreport, name='operationreport'),
    path('salesman/<pk>/', views.salesmandetail, name='salesmandetail'),
    path('salesteam/', views.salesteam, name='salesteam'),
    path('operationstages', views.operationstages, name='operationstages'),
    path('operationstages/<pk>/', views.operationstagedetail, name='operationstagedetail'),
    path('checkv/', views.checkv, name='checkv'),
    path('postreport/', views.orderpostreportthisyear, name='postreport'),
    path('opportunitynotes/<pk>/', views.opportunitynotesn, name='opportunitynotes'),
    path('operationstages/<pk>/<pk1>/', views.salesmanoperationstage, name='salesmanoperationstage'),
    path('postordersnodate/', views.postordersnodate, name='postordersnodate'),
    path('partners/', views.partners, name='partners'),

    path('deal/new/', views.dealnew, name='dealnew'),
    path('dealslist/', views.dealslist, name='dealslist'),
    path('deal/<pk>/', views.dealdetail, name='dealdetail'),
    path('deal/update/<pk>/', views.fastdatadUpdateView.as_view(), name='dealupdate'),
    path('deal/<pk>/delete', views.fastdatadDeleteView.as_view(), name='dealdelete'),
    path('bulkorderupdate', views.bulkorderupdate, name='bulkorderupdate'),
    path('bulkordernew', views.bulkordernew, name='bulkordernew'),

    path('fservice/', views.fservicelist, name='fservicelist'),
    path('fservice/new/', views.CreatefserviceView.as_view(), name='fservicenew'),
    path('fservice/<pk>/', views.fserviceDetailView.as_view(), name='fservicedetail'),
    path('fservice/update/<pk>/', views.fserviceUpdateView.as_view(), name='fserviceupdate'),

    path('fcustomers/', views.fcustomerslist, name='fcustomerslist'),
    path('fcustomer/new/', views.fcustomernew, name='fcustomernew'),
    path('fcustomer/<pk>/', views.fcustomerDetailView.as_view(), name='fcustomerdetail'),
    path('fcustomer/update/<pk>/', views.fcustomerUpdateView.as_view(), name='fcustomerupdate'),

    path('finvoice/', views.finvoicelist, name='finvoicelist'),
    path('finvoice/<pk>/', views.finvoiceDetailView.as_view(), name='finvoicedetail'),
    path('finvoicetemplate/<pk>/', views.finvoicetemplate, name='finvoicetemplate'),
    path('topdf/<pk>/', views.pdfDetail.as_view(), name='topdf'),

    path('fpayment/', views.fpaymentlist, name='fpaymentlist'),

CRMNCC/crm/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class thejobtitle(models.Model):

    jobtitle_name = models.CharField("Project Name",max_length=100,unique=True)

    def __str__(self):
        return str(self.jobtitle_name)






class Profile(models.Model):
    Region_CHOICES = [
                ('Central', 'Central'),
                ('Western', 'Western'),
                ('Eastern', 'Eastern'),

            ]


    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='user_profile')
    phone = models.CharField("Phon No",max_length=100,null=True)
    jobtitle = models.CharField("Job Title",max_length=100,null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',blank=True,null=True)
    role = models.CharField("Role",max_length=200,null=True)
    supervisor = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user_supervisor',null=True)
    jobtitle_detail = models.ForeignKey(thejobtitle,on_delete=models.CASCADE,related_name='jobtitle_profile',null=True)
    region = models.CharField("Region",max_length=20,null=True,choices=Region_CHOICES)


    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

CRMNCC/crm/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class SignupForm(UserCreationForm):


    class Meta:
        model = User
        fields  =['username','email']


class resetForm(forms.Form):
    myemail = forms.EmailField(max_length = 200)

CRMNCC/crm/accounts/views.py
from django.shortcuts import render
from .forms import SignupForm,resetForm
from django.contrib.auth import authenticate,login
from .models import Profile
from django.core.mail import get_connection, send_mail
from django.core.mail.message import EmailMessage
from django.contrib.auth.models import User
from django.http import HttpResponse
import random


def signup(request):
    if request.method=='POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            username = authenticate(username=username,password=password)
            login(request,user)
            return redirect('accounts/profile')
    else:
        form = SignupForm()

    context = {'form':form}
    return render(request, 'registration/signup.html',context)

def profile(request):
    profile = Profile.objects.get(user=request.user)
    context = {'profile':profile}
    return render(request, 'accounts/profile.html',context)


def profile_edit(request):
    pass


def reset(request):

    if request.method=='POST':
        form = resetForm(request.POST)
        if form.is_valid():

            myemail = form.cleaned_data['myemail']
            print(myemail)

            list1 = [1,2,3,4,5,6,7,8,9]
            list2 = ['A','B','C','D','E','F','G','H','J','K']
            list3 = ['q','w','r','g','h','j','y','t','r','e']
            list4 = ['!','@','#','%','&']
            print(list4)
            pas1  = str(list1[random.randrange(len(list1))])
            pas2 = random.choice(list2)
            pas3  = random.choice(list3)
            pas4 = random.choice(list4)
            pas5  = str(random.choice(list1))
            pas6 = random.choice(list2)
            pas7  = random.choice(list3)
            pas8 = random.choice(list4)
            myuser = User.objects.filter(email=myemail).first()

            if myuser is not None :
                print(myuser)
                mynewpassword = pas1 + pas2 + pas3 + pas4 + pas5 + pas6 + pas7 + pas8
                myuser.set_password(mynewpassword)
                myuser.save()
                subject = 'Password Reset'
                body = 'Your new password is ' + mynewpassword
                print('My Paaword',mynewpassword)
                with get_connection(
                host='mail.minaexc.com.sa',
                port=587,
                username='a.abdulbasit@minaexc.com.sa',
                password='abufaisal@mina',
                use_tls=True
                ) as connection:

                    EmailMessage(subject, body, 'a.abdulbasit@minaexc.com.sa', [myemail],
                                 connection=connection).send()

                msg = 'New Password is sent, Please check your email'
                context = {'msg':msg}
                return render(request, 'registration/reset.html',context)
            else:
                msg = 'Your Email is not registered'
                context = {'msg':msg}
                return render(request, 'registration/reset.html',context)


    else:

        form = resetForm()

        context = {'form':form}
        return render(request, 'registration/reset_form.html',context)

CRMNCC/crm/crmapp/templates/crmapp/addservices_confirm_delete.html
{% extends 'crmapp/base.html' %}

{% block content %}

<div class="container mt-5">


<form method="post">{% csrf_token %}
    <p class="text-danger">Are you sure you want to delete </p>
    <br>
    <br>
<h1>  {{ object }}</h1>


    <input type="submit" value="Confirm" class="mt-5 btn btn-danger">
</form>

</div>



{% endblock %}

CRMNCC/crm/crmapp/templates/crmapp/base.html
{% load crmapp_tags %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


  {% block title %} {%endblock%}


</head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top bottom-margin:5px;">

        <button  class="btn  text-white"><a  class="nav-link text-white" href="{% url 'home' %}" >Home</a></button>

      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       Customers
      </a>
       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'customerslist' %}">Customer List</a>
          <!--<a class="dropdown-item" href="{% url 'activityrecordnew' %}">Add Activity</a>-->
          <a class="dropdown-item" href="{% url 'activityrecordlist' %}">Activities List</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'sourcereport' %}">Sources Report</a>
          <a class="dropdown-item" href="{% url 'opportunityhotlead' %}">Hot Lead</a>
          <a class="dropdown-item" href="{% url 'customeroneback' %}">One Back</a>
          {% if user.username|stringformat:"s" == 'basit395' or user.username|stringformat:"s" == 'riyadh' %}
          <a class="dropdown-item" href="{% url 'dealslist' %}">Add Customer</a>
          {% endif %}
        </div>

<div class="btn-group">
  <button type="button" class="btn text-white">Opportunities</button>
  <button type="button" class="btn dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'opportunitylist' %}">Opportunities</a>
    <a class="dropdown-item" href="{% url 'opportunitypost' %}">Post Opportunities</a>
    <a class="dropdown-item" href="{% url 'opportunityhotlead' %}">Hot Leads Opportunities</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#"></a>
     <a class="dropdown-item" href="{% url 'operationstages' %}">Stages Report</a>
  </div>
</div>


<div class="btn-group">
  <button type="button" class="btn text-white">Operation</button>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'operval' %}">Operation Validation</a>
    <a class="dropdown-item" href="{% url 'order' %}">All Orders</a>
    <a class="dropdown-item" href="{% url 'orderopen' %}">Open Orders</a>
    <a class="dropdown-item" href="{% url 'orderheld' %}">Held Orders</a>
    <a class="dropdown-item" href="{% url 'ordercancel' %}">Cancelled  Orders</a>
    <a class="dropdown-item" href="{% url 'orderpost' %}">Post orders</a>
    <a class="dropdown-item" href="{% url 'orderupgrade' %}">Upgrades orders</a>
    <a class="dropdown-item" href="{% url 'orderfingerprint' %}">Fingerprint orders</a>
    <a class="dropdown-item" href="{% url 'billspayment' %}">Order cheking with STC</a>




    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'operationreport' %}">Operation Report</a>

    <a class="dropdown-item" href="{% url 'servicelist' %}">Services</a>
    <a class="dropdown-item" href="{% url 'productreport' %}">Service report</a>
    <a class="dropdown-item" href="{% url 'cctv' %}">CCTV report</a>
  </div>
</div>





<div class="btn-group">
  <button type="button" class="btn text-white">Accounts Payments</button>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'accountlist' %}">Unpaid Accounts</a>
    <a class="dropdown-item" href="{% url 'lastpayments' %}">Paid Accounts</a>
    <a class="dropdown-item" href=""></a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#"></a>
     <a class="dropdown-item" href=""></a>
  </div>
</div>


<!-- operation end -->

<div class="btn-group">
  <button type="button" class="btn text-white">Reports</button>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'report' %}">General Reports</a>
    <a class="dropdown-item" href="{% url 'pipeline' %}">Pipeline</a>
    <a class="dropdown-item" href="{% url 'megapipeline' %}">Mega Pipeline</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'suggestion' %}">Requests</a>
  </div>


</div>



<!-- team start -->

{% if user.user_profile.jobtitle|stringformat:"s" == 'CEO' or user.user_profile.jobtitle|stringformat:"s" == 'GM' or user.user_profile.jobtitle|stringformat:"s" == 'General Manager' or user.user_profile.jobtitle|stringformat:"s" == 'SalesManager' or user.user_profile.jobtitle|stringformat:"s" == 'Board' or user.user_profile.jobtitle|stringformat:"s" == 'OperationV' or user.user_profile.jobtitle|stringformat:"s" == 'accountant'%}


<div class="btn-group">
  <button type="button" class="btn text-white">Team</button>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item text-primary" href="{% url 'stafflist' %}">All users</a>
    <a class="dropdown-item text-primary" href="{% url 'salesteam' %}">Sales Team</a>
    <a class="dropdown-item text-primary" href="{% url 'partners' %}">Partners</a>
    <a class="dropdown-item text-success" href="{% url 'reportcustomerteam' %}">Team-Customers</a>
    <a class="dropdown-item text-success" href="{% url 'reportweaklastweek' %}">Sales Executives Performance Report</a>
    <div class="dropdown-divider"></div>
  </div>
</div>

<a class="nav-link text-white" href="{% url 'dashboard' %}">Dashboard</a>

{% endif %}

<!-- team end -->




{% if user.user_profile.jobtitle|stringformat:"s" == 'CEO' or user.user_profile.jobtitle|stringformat:"s" == 'GM' or user.user_profile.jobtitle|stringformat:"s" == 'General Manager' or user.user_profile.jobtitle|stringformat:"s" == 'accountant' or user.user_profile.jobtitle|stringformat:"s" == 'Board'%}

<div class="btn-group">
  <button type="button" class="btn text-white">Finance</button>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
    <a class="dropdown-item" href="{% url 'postreport' %}">Monthly Post Report</a>
    <a class="dropdown-item" href="{% url 'invoicenew' %}">New Invoice</a>
    <a class="dropdown-item" href="{% url 'invoiceslist' %}">Invoices List</a>
    <a class="dropdown-item" href="{% url 'expensecategorynew' %}">New Category</a>
    <a class="dropdown-item" href="{% url 'expensecategorylist' %}">categories List</a>
    <a class="dropdown-item" href="{% url 'expensesnew' %}">New Expense</a>
    <a class="dropdown-item" href="{% url 'expenseslist' %}">Expenses List</a>
    <a class="dropdown-item" href="{% url 'expensestotal' %}">Expenses Report</a>
    <a class="dropdown-item" href="{% url 'commission' %}">Commission</a>

    <div class="dropdown-divider"></div>
  </div>
</div>
{% endif %}


{% if user.username %}
<button  class="btn btn-outline-dark text-white">{{user.username}}</a></button>
<div class="btn-group">
  <button type="button" class="btn text-white">Settings</button>
  <i class="fa-thin fa-amp-guitar"></i>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu"> <i class="fa fa-cog" aria-hidden="true"></i>
        <a class="nav-link text-primary" href="{% url 'password_change' %}">Password Change<span class="sr-only">(current)</span></a>
        <a class="nav-link text-primary" href="{% url 'logout' %}">Logout<span class="sr-only">(current)</span></a>
        <a class="nav-link text-primary" href="{% url 'emailregister' %}">Email Update<span class="sr-only">(current)</span></a>


  </div>
</div>
{% else %}
<div class="btn-group">
  <button  class="btn btn-outline-dark text-white">Settings</button>
  <button type="button" class="btn text-white dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="sr-only">Toggle Dropdown</span>
  </button>
  <div class="dropdown-menu">
         <a class="nav-link text-primary" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
         <a class="nav-link text-primary" href="{% url 'accounts:reset' %}">Password Reset<span class="sr-only">(current)</span></a>
  </div>
</div>
{% endif %}
</nav>
<div class="container mt-2">

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">
            <h4>{{ message|safe }}</h4>
            <a href="#" class="close">x</a>
            </li>
        {% endfor %}
    </ul>
    {% endif %}

</div>

<br>
<br>

<div class = "container mt-3 w-50">
{% if user.username %}
    <h3 class="text-danger">{% check_email user.username %} </h3>
{% endif %}
</div>


{% block content %}
  {% endblock %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
{% block javascript %}

{% endblock %}


  </body>
</html>